remove ImpredicativeTypes from Core.hs
Was getting this:

API/Core.hs:176:22: error:
    • No instance for (PossibleFacts (forall a. PossibleFacts a => a))
        arising from a use of ‘addToBase’
    • In the expression: addToBase o

This is over-generalizing due to ImpredicativeTypes -- and the extension
doesn't appear to actually be needed.